# devgagan
# Note if you are trying to deploy on vps then directly fill values in ("")

from os import getenv

# VPS --- FILL COOKIES 🍪 in """ ... """ 

INST_COOKIES = """
# wtite up here insta cookies
"""

YTUB_COOKIES = """
# Netscape HTTP Cookie File
# This file was generated by Cookie Editor https://chromewebstore.google.com/detail/cookie-editor/ookdjilphngeeeghgngjabigmpepanpl
.youtube.com	TRUE	/	FALSE	1789972563	SID	g.a0000Qir1nCDL-rMbjvMxySELkfB9i4IdF6xldcQhWBFwYbEPMT596hU1hIprC31isSTust52gACgYKATMSARMSFQHGX2Mif8SYmLJVwMldPEkrm5bRKxoVAUF8yKpa7PPrDreDkHSiEwAKh8Nw0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789972563	__Secure-1PSID	g.a0000Qir1nCDL-rMbjvMxySELkfB9i4IdF6xldcQhWBFwYbEPMT5dKM_YuIJlcvqGTQ5PHJDQAACgYKAf8SARMSFQHGX2MiEOJKzEjER1BmS5ZGSDRA5xoVAUF8yKqnUD2Nq84KZQQG1ZTzjyah0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789972563	__Secure-3PSID	g.a0000Qir1nCDL-rMbjvMxySELkfB9i4IdF6xldcQhWBFwYbEPMT5hy7UNCgCjp9hfL--quFWqgACgYKAVYSARMSFQHGX2MipCQgwxq05xmBpaF0UD25ghoVAUF8yKq1kDTDy_L_TzGkBolRekOo0076
#HttpOnly_.youtube.com	TRUE	/	FALSE	1789972563	HSID	AmY-ngu930ajgREB_
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789972563	SSID	AecvxAJ0-JNyjFgwl
.youtube.com	TRUE	/	FALSE	1789972563	APISID	hJfJE3sZ_EoMpQBr/AkmtoQwu9EygCmvAR
.youtube.com	TRUE	/	TRUE	1789972563	SAPISID	UM1lrVVjfWhOVLEj/A5yA8arPbp6KIQLNy
.youtube.com	TRUE	/	TRUE	1789972563	__Secure-1PAPISID	UM1lrVVjfWhOVLEj/A5yA8arPbp6KIQLNy
.youtube.com	TRUE	/	TRUE	1789972563	__Secure-3PAPISID	UM1lrVVjfWhOVLEj/A5yA8arPbp6KIQLNy
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789972682	LOGIN_INFO	AFmmF2swRQIgb0hmoAY_5KIuky6UW-KgLhWBY-b8FPMYdQ6wLuhpXPsCIQCzb_1vnWZKzWsF3YFR9typYoI77UNjOcUidYAbSHbZtA:QUQ3MjNmeDRkRDNCdkJmdzFkczRmMzU4Y1FncjFvUGNhdHA4b2xPSlEwS3ZOeDRWMG8yVEo4TVN1bnBGaHlrVFQzempSRGZEOUUyT3U0cHFwbWpVQnpNcXVZcWxWaEU0R2NoWlc5d1JUaHA4SS1ucjZveEs2aGZoOVhEV0d0cFJycG11SERBbmpFQzVRVkJnTTkyakJkM2RxQ3NWQ1hzSDdB
.youtube.com	TRUE	/	TRUE	1791714897	PREF	f4=4000000&tz=Asia.Calcutta&f7=100
.youtube.com	TRUE	/	TRUE	1757155871	CONSISTENCY	AKreu9tiBW2oDpZrrfQvJ5n0wC4D8YgetLpgwPm10qWVPquu4AXXjpiwGCewR5fEVI36pipixV1Ve-I--lk513XGG8w7XS4H587AHyLsHhHsRLDkfurKMK8BTJIpI9_lb3mA-z1CJ-65EH0Uu5cDuZuI
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788691513	__Secure-1PSIDTS	sidts-CjIB5H03PwiWyESrwKrOkxJkO1WC_gUywh8nakTOM84L7ufsNa05XSjZkM1hg6X4G5WBAxAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788691513	__Secure-3PSIDTS	sidts-CjIB5H03PwiWyESrwKrOkxJkO1WC_gUywh8nakTOM84L7ufsNa05XSjZkM1hg6X4G5WBAxAA
.youtube.com	TRUE	/	FALSE	1788691584	SIDCC	AKEyXzWUh1wilIWznGACAOsah-tKorLmOQDhnL8ynsSPW0Jyrg9ncPTivxUjJwUNk4eJOE6HymA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788691584	__Secure-1PSIDCC	AKEyXzUl_02BL3oK69SPh9LxHb1BiAL8hp63SekwjPz-aWfsrgFrj8qlNdT-vDcbGXm7wC4KhQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788691584	__Secure-3PSIDCC	AKEyXzVfFrgcRddV4NMwS8AiS8rnEtVbVvEEibYbrZJo-6wriGz0wK77-ucMIWL3v8L2dJrrp8M
"""

API_ID = int(getenv("API_ID", "25331263"))
API_HASH = getenv("API_HASH", "cab85305bf85125a2ac053210bcd1030")
BOT_TOKEN = getenv("BOT_TOKEN", "7898287194:AAH11sDHQdGrkpcLJzRdH1wWul30jsW6x-I")
OWNER_ID = list(map(int, getenv("OWNER_ID", "1955406483").split()))
MONGO_DB = getenv("MONGO_DB", "mongodb+srv://rs92573993688:pVf4EeDuRi2o92ex@cluster0.9u29q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
LOG_GROUP = getenv("LOG_GROUP", "-1002746874071")
CHANNEL_ID = int(getenv("CHANNEL_ID", "-1002888391802"))
BIN_CHANNEL = int(getenv("BIN_CHANNEL", "-1002942104474"))  # Replace with your BIN channel ID
FREEMIUM_LIMIT = int(getenv("FREEMIUM_LIMIT", "3"))
PREMIUM_LIMIT = int(getenv("PREMIUM_LIMIT", "10000"))
WEBSITE_URL = getenv("WEBSITE_URL", "upshrink.com")
AD_API = getenv("AD_API", "52b4a2cf4687d81e7d3f8f2b7bc2943f618e78cb")
STRING = getenv("STRING", None)
YT_COOKIES = getenv("YT_COOKIES", YTUB_COOKIES)
DEFAULT_SESSION = getenv("DEFAUL_SESSION", None)  # added old method of invite link joining
INSTA_COOKIES = getenv("INSTA_COOKIES", INST_COOKIES)
